#!/usr/bin/env sh

CACHED_FILE="$HOME/demo.env"
FILE="$(dirname "$0")/.env"

if [ -f $CACHED_FILE ]; then
    cp $CACHED_FILE $FILE
    echo "$FILE environment file generated."
    exit 0
fi

if [ -f "$FILE" ]; then
    echo "$FILE environment file exists."
    echo "Please remove it before generating a new one or use existing one."
    exit 1
fi

POSTGRES_PASSWORD="$(head -c 12 /dev/random  | base64 | tr -d =+/)"
CLOVER_SESSION_SECRET="$(head -c 64 /dev/random | base64)"
CLOVER_COLUMN_ENCRYPTION_KEY="$(head -c 32 /dev/random | base64)"

read -sp "Enter Hetzner Username: " HETZNER_USER
echo ""
read -sp "Enter Hetzner Password: " HETZNER_PASSWORD
echo ""
read -sp "Enter PostgreSQL Image SAS token: " PG_SAS_TOKEN

cat <<EOT > $(dirname "$0")/.env
RACK_ENV=development
POSTGRES_DB=clover
POSTGRES_PASSWORD="$POSTGRES_PASSWORD"
CLOVER_DATABASE_URL="postgres://postgres/clover?user=clover&password=${POSTGRES_PASSWORD}"
CLOVER_SESSION_SECRET="$CLOVER_SESSION_SECRET"
CLOVER_COLUMN_ENCRYPTION_KEY="$CLOVER_COLUMN_ENCRYPTION_KEY"
MINIO_SERVICE_PROJECT_ID=5fa15c7c-3e3d-86d2-96f8-1aa96200c486
POSTGRES_SERVICE_PROJECT_ID=c2dd42ae-1ddc-82d2-8907-e2136776cfd5
POSTGRES_SERVICE_BLOB_STORAGE_ID=553c6522-1cef-828c-b18a-fd8ef83728fe
HETZNER_USER="$HETZNER_USER"
HETZNER_PASSWORD="$HETZNER_PASSWORD"
PG_SAS_TOKEN="$PG_SAS_TOKEN"
EOT

cp $FILE $CACHED_FILE
echo "$FILE environment file generated."
